### ISSUE TITLE
failed with Exception

### ISSUE THREAD

**Issue by Joseph-Nathan** [kaex/youtube_video_info#1]
E/flutter (17111): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: NoSuchMethodError: The method 'toDouble' was called on null.
E/flutter (17111): Receiver: null
E/flutter (17111): Tried calling: toDouble()
E/flutter (17111): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter (17111): #1      new YoutubeDataModel.fromMap (package:youtube_video_info/model.dart:54:46)
E/flutter (17111): #2      YoutubeData.getData (package:youtube_video_info/youtube.dart:37:29)
E/flutter (17111): <asynchronous suspension>

**Comment by kaex** [comment]
Thank you, this should be fixed with version `1.0.1`
