### ISSUE TITLE
Unhandled Exception: SocketException: OS Error: Connection reset by peer, errno = 104, address =  port = 59210

### ISSUE THREAD

**Issue by Joseph-Nathan** [kaex/youtube_video_info#2]
E/flutter (14910): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: OS Error: Connection reset by peer, errno = 104, address = youtu.be, port = 59210
E/flutter (14910): #0      YoutubeData.getData (package:youtube_video_info/youtube.dart:21:7)
E/flutter (14910): <asynchronous suspension>

**Comment by kaex** [comment]
It may be your ISP blocking the connection.

Maybe a simple `flutter clean` might solve the issue. If not, you can also try `flutter pub cache repair`.

There are no issues with the package, an issue on your side.

**Comment by Joseph-Nathan** [comment]
thanks bro , as you mention ISP was bad in that time .
